version: "3.9"
services:
  identity:
    build: .
    ports:
      - "4000:4000"
    command: npm run dev
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=identity
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"