version: "3.9"
services:
  identity:
    build: .
    command: npm run start
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=identity